import {
  AppWindow,
  Binary,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Cloud,
  Component,
  Cpu,
  Database,
  DatabaseZap,
  Infinity,
  Layers,
  Lightbulb,
  MonitorCog,
  Network,
  ScrollText,
  Server,
  ShieldCheck,
  Trophy,
  Workflow,
  type LucideIcon,
} from "lucide-react";

export type Category = {
  slug: string;
  name: string;
  blurb: string;
  /** The syllabus, in study order. Each day is logged under one of these. */
  topics: readonly string[];
  /** No fixed syllabus: each day's topic is whatever it covered (a paper, a fact…). */
  freeform?: boolean;
  Icon: LucideIcon;
};

/**
 * The cards on the Learning Journey tab, in order. Each one gets a page at
 * /learning/<slug> listing its topics, with the days logged under each.
 */
export const categories = [
  {
    slug: "dsa",
    name: "DSA & Advanced Algos",
    blurb: "Patterns, problems and the intuition behind them, all the way to the advanced stuff.",
    topics: [
      "Basics & Beginner Problems",
      "Sorting",
      "Arrays",
      "Hashing",
      "Binary Search",
      "Strings",
      "Recursion",
      "Linked Lists",
      "Bit Manipulation",
      "Greedy Algorithms",
      "Sliding Window & Two Pointers",
      "Stacks & Queues",
      "Binary Trees",
      "Binary Search Trees",
      "Heaps",
      "Graphs",
      "Dynamic Programming",
      "Tries",
      "Math",
      "Number Theory",
      "Combinatorics",
      "Advanced Data Structures",
      "Game Theory",
      "Geometry",
      "Miscellaneous",
    ],
    Icon: Binary,
  },
  {
    slug: "cpp-oops",
    name: "C++ & OOPs",
    blurb: "Modern C++, the STL and object-oriented design done right.",
    topics: [
      "C++ Basics & Functions",
      "Debugging",
      "Data Types, Constants & Strings",
      "Operators & Bit Manipulation",
      "Scope, Duration & Linkage",
      "Control Flow & Error Handling",
      "Type Conversion & Deduction",
      "Overloading, Templates & constexpr",
      "References & Pointers",
      "Enums & Structs",
      "Classes & Objects (OOPS 1)",
      "std::vector & Arrays",
      "STL Containers, Iterators & Algorithms",
      "Dynamic Allocation",
      "Function Pointers, Recursion & Lambdas",
      "Operator Overloading (OOPS 2)",
      "Move Semantics & Smart Pointers",
      "Object Relationships (OOPS 3)",
      "Inheritance (OOPS 4)",
      "Virtual Functions & Polymorphism (OOPS 5)",
      "Templates & Classes (OOPS 6)",
      "Exceptions",
      "Input/Output & Streams",
      "Modern C++ (11–23)",
    ],
    Icon: Braces,
  },
  {
    slug: "computer-architecture",
    name: "Computer Architecture",
    blurb: "What actually happens inside the processor.",
    topics: [
      "Data Representation",
      "Instruction Set Architecture",
      "CPU Datapath",
      "Pipelining & Hazards",
      "Memory Hierarchy",
      "Caches",
      "Virtual Memory & TLB",
      "I/O & Interrupts",
      "Multicore & Parallelism",
    ],
    Icon: Cpu,
  },
  {
    slug: "operating-systems",
    name: "Operating Systems",
    blurb: "Processes, memory and the scheduler that juggles it all.",
    topics: [
      "Processes & Threads",
      "CPU Scheduling",
      "Synchronization & Locks",
      "Deadlocks",
      "Memory Management",
      "Paging & Virtual Memory",
      "File Systems",
      "I/O & Storage",
      "Linux Internals",
    ],
    Icon: MonitorCog,
  },
  {
    slug: "computer-networks",
    name: "Computer Networks",
    blurb: "How bytes find their way across the internet.",
    topics: [
      "OSI & TCP/IP Models",
      "Physical & Data Link Layers",
      "IP & Subnetting",
      "Routing",
      "TCP & UDP",
      "DNS",
      "HTTP & HTTPS",
      "TLS & Network Security",
      "Sockets",
      "CDNs & Load Balancers",
    ],
    Icon: Network,
  },
  {
    slug: "dbms",
    name: "DBMS",
    blurb: "Storing data so it stays correct, consistent and fast.",
    topics: [
      "ER Modeling",
      "Relational Model & SQL",
      "Normalization",
      "Indexing & B+ Trees",
      "Transactions & ACID",
      "Concurrency Control",
      "Recovery",
      "Query Processing",
      "NoSQL & CAP",
    ],
    Icon: Database,
  },
  {
    slug: "system-design-lld",
    name: "System Design — LLD",
    blurb: "Clean classes, interfaces and the patterns that hold them together.",
    topics: [
      "OOP Design & SOLID",
      "UML & Class Diagrams",
      "Creational Patterns",
      "Structural Patterns",
      "Behavioral Patterns",
      "Concurrency in LLD",
      "Machine Coding Problems",
    ],
    Icon: Component,
  },
  {
    slug: "system-design-hld",
    name: "System Design — HLD & Distributed Systems",
    blurb:
      "Architecting systems that scale to millions of users, and the distributed-systems ideas underneath.",
    topics: [
      "Scalability Basics",
      "Load Balancing",
      "Caching",
      "Message Queues",
      "Microservices",
      "Rate Limiting",
      "Why Distributed Is Hard",
      "Time, Clocks & Ordering",
      "Replication",
      "Databases, Partitioning & Sharding",
      "Consistency Models",
      "Consensus: Paxos & Raft",
      "Distributed Transactions",
      "Fault Tolerance",
      "Case Studies",
    ],
    Icon: Boxes,
  },
  {
    slug: "ml-dl",
    name: "ML & DL Concepts",
    blurb: "The math and intuition behind machine and deep learning.",
    topics: [
      "Linear & Logistic Regression",
      "Bias–Variance & Regularization",
      "Decision Trees & Ensembles",
      "SVMs",
      "Clustering & PCA",
      "Neural Networks & Backprop",
      "Optimizers",
      "CNNs",
      "RNNs & LSTMs",
      "Attention",
    ],
    Icon: Brain,
  },
  {
    slug: "research-papers",
    name: "Research Paper Summarizations",
    blurb: "Dense papers, distilled into what actually matters.",
    topics: [],
    freeform: true,
    Icon: ScrollText,
  },
  {
    slug: "software-engineering",
    name: "Software Engineering",
    blurb: "Building, shipping and maintaining real software.",
    topics: [
      "Git & Version Control",
      "Testing",
      "CI/CD",
      "Clean Code & Refactoring",
      "Code Review",
      "Debugging & Observability",
      "APIs & REST",
      "Docker & Deployment",
    ],
    Icon: Layers,
  },
  {
    slug: "ai-llms",
    name: "AI & LLMs",
    blurb: "How LLMs work under the hood, and how to build with them.",
    topics: [
      "Tokenization & Embeddings",
      "Transformers",
      "Pretraining & Scaling Laws",
      "Fine-tuning & RLHF",
      "Prompting",
      "RAG",
      "Agents & Tool Use",
      "Evals",
      "Inference & Serving",
    ],
    Icon: BrainCircuit,
  },
  {
    slug: "backend-engineering",
    name: "Backend Engineering",
    blurb: "Servers, APIs and everything behind the screen.",
    topics: [
      "How the Web Works",
      "HTTP & REST APIs",
      "Authentication: Sessions, JWT & OAuth",
      "Databases & ORMs",
      "Caching",
      "Background Jobs & Queues",
      "API Design & Versioning",
      "GraphQL & gRPC",
      "Testing Backends",
      "Performance & Profiling",
    ],
    Icon: Server,
  },
  {
    slug: "frontend-engineering",
    name: "Frontend Engineering",
    blurb: "Building fast, accessible interfaces people enjoy using.",
    topics: [
      "HTML & Accessibility",
      "CSS & Layout",
      "JavaScript in Depth",
      "TypeScript",
      "React",
      "State Management",
      "Rendering: SSR, SSG & Next.js",
      "How Browsers Work",
      "Web Performance",
      "Testing UIs",
    ],
    Icon: AppWindow,
  },
  {
    slug: "cloud-computing",
    name: "Cloud Computing",
    blurb: "Renting the world's computers, and using them well.",
    topics: [
      "Cloud Fundamentals",
      "Compute: VMs, Containers & Serverless",
      "Storage & CDNs",
      "Networking: VPCs & Load Balancers",
      "Managed Databases",
      "Identity & Access (IAM)",
      "Infrastructure as Code",
      "Cost & Autoscaling",
      "High Availability & Multi-Region",
    ],
    Icon: Cloud,
  },
  {
    slug: "devops-sre",
    name: "DevOps & SRE",
    blurb: "Shipping often, and keeping it running.",
    topics: [
      "Linux & the Shell",
      "CI/CD Pipelines",
      "Docker",
      "Kubernetes",
      "Observability: Logs, Metrics & Traces",
      "SLIs, SLOs & Error Budgets",
      "Incident Response & Postmortems",
      "Release Strategies",
      "Chaos Engineering",
    ],
    Icon: Infinity,
  },
  {
    slug: "mlops",
    name: "MLOps",
    blurb: "Taking models from a notebook to production.",
    topics: [
      "The ML Lifecycle",
      "Data & Feature Pipelines",
      "Experiment Tracking",
      "Training at Scale",
      "Model Registry & Versioning",
      "Serving & Inference",
      "Monitoring & Drift",
      "LLMOps",
    ],
    Icon: Workflow,
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    blurb: "How systems get broken into, and how to stop it.",
    topics: [
      "Security Fundamentals",
      "Cryptography Basics",
      "Web Security & the OWASP Top 10",
      "Authentication & Authorization",
      "Network Security",
      "Secure Coding",
      "Threat Modeling",
      "CTFs & Pentesting Basics",
    ],
    Icon: ShieldCheck,
  },
  {
    slug: "data-engineering",
    name: "Data Engineering",
    blurb: "Moving and shaping data at scale.",
    topics: [
      "Data Modeling",
      "SQL for Analytics",
      "ETL & ELT",
      "Batch Processing with Spark",
      "Stream Processing: Kafka & Flink",
      "Warehouses & Lakehouses",
      "Orchestration with Airflow",
      "Data Quality & Governance",
    ],
    Icon: DatabaseZap,
  },
  {
    slug: "cool-things",
    name: "Cool Things to Know!",
    blurb: "Fun, surprising things we picked up along the way.",
    topics: [],
    freeform: true,
    Icon: Lightbulb,
  },
  {
    slug: "ai-race",
    name: "AI Race — Who Will Win?",
    blurb: "Tracking the labs, models and moves shaping the race.",
    topics: [],
    freeform: true,
    Icon: Trophy,
  },
] as const satisfies readonly Category[];

export type CategorySlug = (typeof categories)[number]["slug"];

export function getCategory(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug);
}
