import {
  Binary,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Component,
  Cpu,
  Database,
  Layers,
  Lightbulb,
  MonitorCog,
  Network,
  ScrollText,
  Trophy,
  type LucideIcon,
} from "lucide-react";

export type Category = {
  slug: string;
  name: string;
  blurb: string;
  /** The syllabus, in study order. Each day is logged under one of these. */
  topics: readonly string[];
  /** No fixed syllabus: each day's topic is whatever it covered (a paper, a fact…). */
  freeform?: boolean;
  Icon: LucideIcon;
};

/**
 * The cards on the Learning Journey tab, in order. Each one gets a page at
 * /learning/<slug> listing its topics, with the days logged under each.
 */
export const categories = [
  {
    slug: "dsa",
    name: "DSA & Advanced Algos",
    blurb: "Patterns, problems and the intuition behind them, all the way to the advanced stuff.",
    topics: [
      "Basics & Beginner Problems",
      "Sorting",
      "Arrays",
      "Hashing",
      "Binary Search",
      "Strings (Basic & Medium)",
      "Recursion",
      "Linked Lists",
      "Bit Manipulation",
      "Greedy Algorithms",
      "Sliding Window & Two Pointers",
      "Stacks & Queues",
      "Binary Trees",
      "Binary Search Trees",
      "Heaps",
      "Graphs",
      "Dynamic Programming",
      "Tries",
      "Strings (Advanced Algorithms)",
      "Math",
      "Number Theory",
      "Combinatorics",
      "Advanced Data Structures",
      "Game Theory",
      "Geometry",
      "Miscellaneous",
    ],
    Icon: Binary,
  },
  {
    slug: "cpp-oops",
    name: "C++ & OOPs",
    blurb: "Modern C++, the STL and object-oriented design done right.",
    topics: [
      "C++ Basics & Pointers",
      "References & Memory",
      "Classes & Objects",
      "Inheritance & Polymorphism",
      "Virtual Functions & vtables",
      "Templates",
      "STL Containers",
      "STL Algorithms & Iterators",
      "Smart Pointers & RAII",
      "Move Semantics",
      "Modern C++ (11–20)",
    ],
    Icon: Braces,
  },
  {
    slug: "computer-architecture",
    name: "Computer Architecture",
    blurb: "What actually happens inside the processor.",
    topics: [
      "Data Representation",
      "Instruction Set Architecture",
      "CPU Datapath",
      "Pipelining & Hazards",
      "Memory Hierarchy",
      "Caches",
      "Virtual Memory & TLB",
      "I/O & Interrupts",
      "Multicore & Parallelism",
    ],
    Icon: Cpu,
  },
  {
    slug: "operating-systems",
    name: "Operating Systems",
    blurb: "Processes, memory and the scheduler that juggles it all.",
    topics: [
      "Processes & Threads",
      "CPU Scheduling",
      "Synchronization & Locks",
      "Deadlocks",
      "Memory Management",
      "Paging & Virtual Memory",
      "File Systems",
      "I/O & Storage",
      "Linux Internals",
    ],
    Icon: MonitorCog,
  },
  {
    slug: "computer-networks",
    name: "Computer Networks",
    blurb: "How bytes find their way across the internet.",
    topics: [
      "OSI & TCP/IP Models",
      "Physical & Data Link Layers",
      "IP & Subnetting",
      "Routing",
      "TCP & UDP",
      "DNS",
      "HTTP & HTTPS",
      "TLS & Network Security",
      "Sockets",
      "CDNs & Load Balancers",
    ],
    Icon: Network,
  },
  {
    slug: "dbms",
    name: "DBMS",
    blurb: "Storing data so it stays correct, consistent and fast.",
    topics: [
      "ER Modeling",
      "Relational Model & SQL",
      "Normalization",
      "Indexing & B+ Trees",
      "Transactions & ACID",
      "Concurrency Control",
      "Recovery",
      "Query Processing",
      "NoSQL & CAP",
    ],
    Icon: Database,
  },
  {
    slug: "system-design-lld",
    name: "System Design — LLD",
    blurb: "Clean classes, interfaces and the patterns that hold them together.",
    topics: [
      "OOP Design & SOLID",
      "UML & Class Diagrams",
      "Creational Patterns",
      "Structural Patterns",
      "Behavioral Patterns",
      "Concurrency in LLD",
      "Machine Coding Problems",
    ],
    Icon: Component,
  },
  {
    slug: "system-design-hld",
    name: "System Design — HLD",
    blurb: "Architecting services that scale to millions of users.",
    topics: [
      "Scalability Basics",
      "Load Balancing",
      "Caching",
      "Databases & Sharding",
      "Replication & Consistency",
      "Message Queues",
      "Microservices",
      "Rate Limiting",
      "Case Studies",
    ],
    Icon: Boxes,
  },
  {
    slug: "ml-dl",
    name: "ML & DL Concepts",
    blurb: "The math and intuition behind machine and deep learning.",
    topics: [
      "Linear & Logistic Regression",
      "Bias–Variance & Regularization",
      "Decision Trees & Ensembles",
      "SVMs",
      "Clustering & PCA",
      "Neural Networks & Backprop",
      "Optimizers",
      "CNNs",
      "RNNs & LSTMs",
      "Attention",
    ],
    Icon: Brain,
  },
  {
    slug: "research-papers",
    name: "Research Paper Summarizations",
    blurb: "Dense papers, distilled into what actually matters.",
    topics: [],
    freeform: true,
    Icon: ScrollText,
  },
  {
    slug: "software-engineering",
    name: "Software Engineering",
    blurb: "Building, shipping and maintaining real software.",
    topics: [
      "Git & Version Control",
      "Testing",
      "CI/CD",
      "Clean Code & Refactoring",
      "Code Review",
      "Debugging & Observability",
      "APIs & REST",
      "Docker & Deployment",
    ],
    Icon: Layers,
  },
  {
    slug: "ai-llms",
    name: "AI & LLMs",
    blurb: "How LLMs work under the hood, and how to build with them.",
    topics: [
      "Tokenization & Embeddings",
      "Transformers",
      "Pretraining & Scaling Laws",
      "Fine-tuning & RLHF",
      "Prompting",
      "RAG",
      "Agents & Tool Use",
      "Evals",
      "Inference & Serving",
    ],
    Icon: BrainCircuit,
  },
  {
    slug: "cool-things",
    name: "Cool Things to Know!",
    blurb: "Fun, surprising things I picked up along the way.",
    topics: [],
    freeform: true,
    Icon: Lightbulb,
  },
  {
    slug: "ai-race",
    name: "AI Race — Who Will Win?",
    blurb: "Tracking the labs, models and moves shaping the race.",
    topics: [],
    freeform: true,
    Icon: Trophy,
  },
] as const satisfies readonly Category[];

export type CategorySlug = (typeof categories)[number]["slug"];

export function getCategory(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug);
}
