import { getCategory } from "./categories";

export type TopicGuide = {
  /** A category slug from categories.ts. */
  category: string;
  /** Exactly as in that category's topics list. */
  topic: string;
  /** The page lives at /learning/<category>/<slug>. Don't change it once it's live. */
  slug: string;
  blurb: string;
  /** In study order. */
  subtopics: readonly string[];
};

const cpp = (topic: string, slug: string, blurb: string, subtopics: readonly string[]): TopicGuide => ({
  category: "cpp-oops",
  topic,
  slug,
  blurb,
  subtopics,
});

/**
 * Topics broken into subtopics. A topic listed here gets its own page, linked
 * from its card on the category page.
 */
export const guides: readonly TopicGuide[] = [
  cpp(
    "C++ Basics & Functions",
    "cpp-basics-and-functions",
    "Everything before types get serious: how a C++ program gets built, variables and console I/O, and splitting code into functions and files.",
    [
      "What C++ is",
      "From source code to a running program",
      "Setting up the compiler",
      "Compiling from the command line",
      "Statements and program structure",
      "Variables and initialization",
      "Console input and output",
      "Uninitialized variables and undefined behavior",
      "Identifiers, keywords and formatting",
      "Literals, operators and expressions",
      "Functions, return values and parameters",
      "Local scope and using functions well",
      "Forward declarations and multiple files",
      "Namespaces",
      "Preprocessor, headers and header guards",
      "Static and dynamic libraries",
      "Build systems: Make and CMake",
      "Designing your first programs",
    ],
  ),
  cpp(
    "Debugging",
    "debugging",
    "Finding and fixing bugs on purpose, from print statements and debuggers to sanitizers and static analysis.",
    [
      "Syntax errors vs semantic errors",
      "Reading compiler error messages",
      "A systematic debugging process",
      "Print debugging and logging",
      "Stepping through code",
      "Breakpoints and run-to-cursor",
      "Watching variables",
      "Reading the call stack",
      "Debugging with gdb and lldb",
      "AddressSanitizer and UBSan",
      "Finding memory leaks with Valgrind",
      "Static analysis with clang-tidy",
      "Defensive habits that prevent bugs",
    ],
  ),
  cpp(
    "Data Types, Constants & Strings",
    "data-types-constants-and-strings",
    "The built-in types and how they really behave, constants and compile-time values, and working with text.",
    [
      "The fundamental types at a glance",
      "void",
      "Object sizes and sizeof",
      "Signed integers and overflow",
      "Unsigned integers and their traps",
      "Fixed-width integers and size_t",
      "Type limits with std::numeric_limits",
      "Scientific notation",
      "Floating-point numbers and precision",
      "Booleans and a first look at if",
      "Characters and char",
      "Converting types with static_cast",
      "Const variables",
      "Literals and literal suffixes",
      "Binary, octal and hexadecimal",
      "The as-if rule and optimization",
      "Constant expressions",
      "constexpr variables",
      "std::string basics",
      "Working with std::string",
      "std::string_view",
      "Converting between strings and numbers",
      "Character handling with <cctype>",
      "Unicode and wide character types",
    ],
  ),
  cpp(
    "Operators & Bit Manipulation",
    "operators-and-bit-manipulation",
    "How expressions get evaluated, every family of operators, and working with individual bits.",
    [
      "Precedence and associativity",
      "Arithmetic and integer division",
      "Remainder and exponentiation",
      "Increment, decrement and side effects",
      "Order of evaluation pitfalls",
      "The comma operator",
      "The conditional operator ?:",
      "Comparisons and floating-point pitfalls",
      "Logical operators and short-circuiting",
      "Bit flags with std::bitset",
      "Bitwise operators",
      "Bit masks",
      "Binary to decimal and back",
      "The <bit> header (C++20)",
    ],
  ),
  cpp(
    "Scope, Duration & Linkage",
    "scope-duration-and-linkage",
    "Where a name is visible, how long an object lives, and how names connect across files.",
    [
      "Blocks and nested scopes",
      "User-defined namespaces",
      "Local variables: scope and lifetime",
      "Global variables",
      "Variable shadowing",
      "Internal linkage",
      "External linkage and extern",
      "Why mutable globals are risky",
      "The One Definition Rule",
      "Inline functions and variables",
      "Sharing constants across files",
      "Static local variables",
      "Static initialization order",
      "thread_local variables",
      "using declarations and directives",
      "Unnamed and inline namespaces",
      'Name mangling and extern "C"',
      "Scope, duration and linkage recap",
    ],
  ),
  cpp(
    "Control Flow & Error Handling",
    "control-flow-and-error-handling",
    "Branches, loops and jumps, random numbers, and testing and validating what your program does.",
    [
      "How control flow works",
      "if statements and blocks",
      "Common if-statement mistakes",
      "if and switch with initializers",
      "if constexpr",
      "switch statements",
      "Fallthrough and scope in switch",
      "goto, and why to avoid it",
      "while loops",
      "do-while loops",
      "for loops",
      "break and continue",
      "Exiting early: exit, abort, terminate",
      "Random number generation",
      "The Mersenne Twister",
      "A reusable random number helper",
      "Testing your code",
      "Code coverage",
      "Common semantic errors",
      "Detecting and handling errors",
      "Handling invalid input from std::cin",
      "assert and static_assert",
      "Unit testing with GoogleTest and Catch2",
    ],
  ),
  cpp(
    "Type Conversion & Deduction",
    "type-conversion-and-deduction",
    "Every way a value changes type, implicitly or on purpose, and letting the compiler work types out for you.",
    [
      "Implicit type conversion",
      "Numeric promotions",
      "Numeric conversions",
      "Narrowing and brace initialization",
      "The usual arithmetic conversions",
      "Explicit casts with static_cast",
      "const_cast and reinterpret_cast",
      "Why to avoid C-style casts",
      "typedefs and type aliases",
      "auto for variables",
      "auto and trailing return types",
      "decltype and decltype(auto)",
    ],
  ),
  cpp(
    "Overloading, Templates & constexpr",
    "overloading-templates-and-constexpr",
    "One name for many functions, functions written once for any type, and code that runs at compile time.",
    [
      "Function overloading",
      "How overloads are told apart",
      "Overload resolution and ambiguity",
      "Deleted functions",
      "Default arguments",
      "Function templates",
      "How templates are instantiated",
      "Templates with several type parameters",
      "Abbreviated templates with auto",
      "Non-type template parameters",
      "Templates across multiple files",
      "constexpr functions",
      "When constexpr runs at compile time",
      "consteval functions",
      "constinit",
    ],
  ),
  cpp(
    "References & Pointers",
    "references-and-pointers",
    "Lvalues and rvalues, references and pointers, and choosing how data goes in and out of functions.",
    [
      "Compound types",
      "Value categories: lvalues and rvalues",
      "Lvalue references",
      "References to const",
      "Pass by reference",
      "Pass by const reference",
      "Pointers",
      "Null pointers and nullptr",
      "Pointers and const",
      "Pass by address",
      "Return by reference or address",
      "In and out parameters",
      "Dangling pointers and references",
      "Pointers vs references",
      "auto with references and pointers",
      "std::optional",
    ],
  ),
  cpp(
    "Enums & Structs",
    "enums-and-structs",
    "Your own types: enumerations, structs, unions, and a first look at class templates.",
    [
      "Program-defined types",
      "Unscoped enumerations",
      "Enums and integer conversions",
      "Enums to and from strings",
      "A first look at overloading << and >>",
      "Scoped enums (enum class)",
      "Structs and member access",
      "Aggregate initialization",
      "Designated initializers",
      "Default member initializers",
      "Passing and returning structs",
      "Padding and alignment",
      "Member access through pointers",
      "Structured bindings",
      "std::pair and std::tuple",
      "Unions",
      "A first look at class templates",
      "CTAD and deduction guides",
      "Alias templates",
      "Reading the language reference",
    ],
  ),
  cpp(
    "Classes & Objects (OOPS 1)",
    "classes-and-objects",
    "Bundling data with behaviour: classes, constructors, encapsulation and the special member functions.",
    [
      "What object-oriented programming is",
      "Classes vs structs",
      "Member functions",
      "const member functions",
      "mutable members",
      "Access specifiers",
      "Getters and setters",
      "Returning references to members",
      "Encapsulation and data hiding",
      "Constructors",
      "Member initializer lists",
      "Default constructors",
      "Delegating constructors",
      "Temporary objects",
      "Copy constructors",
      "Copy elision and RVO",
      "Converting constructors and explicit",
      "= default and = delete",
      "constexpr classes",
      "The this pointer and chaining",
      "Classes in header and source files",
      "Nested types",
      "Destructors",
      "Member functions of class templates",
      "Static member variables",
      "Static member functions",
      "Friend functions",
      "Friend classes",
      "Ref qualifiers",
    ],
  ),
  cpp(
    "std::vector & Arrays",
    "std-vector-and-arrays",
    "Contiguous collections: std::vector, std::array, C-style arrays, and views over them.",
    [
      "Containers and arrays",
      "std::vector basics",
      "Signed vs unsigned indices",
      "Passing std::vector",
      "Returning vectors and moving",
      "Looping over arrays",
      "Range-based for loops",
      "Indexing with enumerators",
      "Size, capacity and how vector grows",
      "push_back vs emplace_back",
      "Using a vector as a stack",
      "std::vector<bool>",
      "std::array basics",
      "std::array length and indexing",
      "Passing and returning std::array",
      "std::array of class types",
      "std::reference_wrapper",
      "std::array with enumerations",
      "C-style arrays",
      "Array decay",
      "Pointer arithmetic",
      "C-style strings",
      "Multidimensional arrays",
      "Multidimensional std::array",
      "std::span",
    ],
  ),
  cpp(
    "STL Containers, Iterators & Algorithms",
    "stl-containers-iterators-and-algorithms",
    "The rest of the standard library's containers, the iterators that walk them, and the algorithms that work on all of them.",
    [
      "The STL at a glance",
      "Sorting by hand: selection sort",
      "Iterators",
      "Iterator categories",
      "Iterator invalidation",
      "deque, list and forward_list",
      "stack, queue and priority_queue",
      "set and multiset",
      "map and multimap",
      "unordered_set and unordered_map",
      "Custom comparators and hashes",
      "Choosing the right container",
      "Standard algorithms",
      "Sorting and searching algorithms",
      "Modifying algorithms and erase-remove",
      "Numeric algorithms",
      "Heap and partition algorithms",
      "Ranges and views (C++20)",
      "Timing your code",
    ],
  ),
  cpp(
    "Dynamic Allocation",
    "dynamic-allocation",
    "Memory you manage yourself: the stack and the heap, new and delete, and everything that goes wrong.",
    [
      "The stack and the heap",
      "new and delete",
      "Dynamic arrays with new[]",
      "Destructors and cleanup",
      "Pointers to pointers",
      "Dynamic multidimensional arrays",
      "void pointers",
      "Leaks, dangling and double deletes",
      "new/delete vs malloc/free",
      "Placement new",
      "Overloading new and delete",
      "Allocators and memory pools",
    ],
  ),
  cpp(
    "Function Pointers, Recursion & Lambdas",
    "function-pointers-recursion-and-lambdas",
    "Functions as values, functions that call themselves, and functions written right where they're used.",
    [
      "Function pointers",
      "Callbacks and std::function",
      "Recursion",
      "Command-line arguments",
      "Ellipsis and why to avoid it",
      "Lambdas",
      "Lambda captures",
      "Generic lambdas",
      "Lambdas with STL algorithms",
      "std::invoke and std::bind",
    ],
  ),
  cpp(
    "Operator Overloading (OOPS 2)",
    "operator-overloading",
    "Making your own types work with the built-in operators, and copying them correctly.",
    [
      "Operator overloading basics",
      "Overloading with friend functions",
      "Overloading with normal functions",
      "Overloading << and >>",
      "Overloading with member functions",
      "Unary operators",
      "Comparison operators",
      "The spaceship operator <=>",
      "Increment and decrement",
      "The subscript operator []",
      "The call operator () and functors",
      "Conversion operators",
      "Overloading -> and *",
      "The assignment operator",
      "Shallow vs deep copy",
      "The copy-and-swap idiom",
      "Operators and function templates",
      "Rules and good practice",
      "Project: a fully overloaded class",
    ],
  ),
  cpp(
    "Move Semantics & Smart Pointers",
    "move-semantics-and-smart-pointers",
    "Transferring ownership instead of copying, and letting objects clean up after themselves.",
    [
      "Why smart pointers and moves exist",
      "RAII",
      "Rvalue references",
      "Move constructor and move assignment",
      "std::move",
      "The rule of three, five and zero",
      "std::unique_ptr",
      "std::shared_ptr",
      "make_unique and make_shared",
      "Custom deleters",
      "std::weak_ptr and reference cycles",
      "Forwarding references",
      "Perfect forwarding with std::forward",
    ],
  ),
  cpp(
    "Object Relationships (OOPS 3)",
    "object-relationships",
    "How objects relate to one another, and who owns what.",
    [
      "Kinds of object relationships",
      "Composition",
      "Aggregation",
      "Association",
      "Dependencies",
      "Ownership and lifetimes",
      "Container classes",
      "std::initializer_list",
      "Composition over inheritance",
    ],
  ),
  cpp(
    "Inheritance (OOPS 4)",
    "inheritance",
    "Building new classes on top of existing ones, and exactly what a derived class gets from its base.",
    [
      "What inheritance is",
      "Basic inheritance",
      "Order of construction and destruction",
      "Initializing the base class",
      "Inheriting constructors",
      "Access specifiers in inheritance",
      "Adding to a derived class",
      "Overriding inherited functions",
      "Hiding inherited members",
      "Multiple inheritance",
    ],
  ),
  cpp(
    "Virtual Functions & Polymorphism (OOPS 5)",
    "virtual-functions-and-polymorphism",
    "One interface, many behaviours: virtual dispatch, how it works under the hood, and its alternatives.",
    [
      "Base pointers to derived objects",
      "Virtual functions",
      "override, final and covariant returns",
      "Virtual destructors",
      "Early and late binding",
      "The virtual table",
      "Virtual calls in constructors",
      "Pure virtual functions and interfaces",
      "Virtual base classes and the diamond",
      "Object slicing",
      "dynamic_cast",
      "RTTI and typeid",
      "Printing derived classes with <<",
      "Static polymorphism with CRTP",
      "The cost of virtual calls",
      "Type erasure",
    ],
  ),
  cpp(
    "Templates & Classes (OOPS 6)",
    "templates-and-classes",
    "Generic classes and the full template toolkit, from specialization to concepts.",
    [
      "Class templates",
      "Non-type parameters in class templates",
      "Function template specialization",
      "Class template specialization",
      "Partial specialization",
      "Partial specialization for pointers",
      "Dependent names and typename",
      "Variadic templates",
      "Fold expressions",
      "Template template parameters",
      "Type traits",
      "SFINAE and enable_if",
      "Concepts and requires",
      "Template metaprogramming basics",
    ],
  ),
  cpp(
    "Exceptions",
    "exceptions",
    "Signalling and recovering from errors, and writing code that stays correct when something fails.",
    [
      "Why exceptions exist",
      "throw, try and catch",
      "Stack unwinding",
      "Uncaught exceptions and catch-all",
      "Exceptions and class hierarchies",
      "The standard exception types",
      "Rethrowing exceptions",
      "Function try blocks",
      "Throwing in constructors and destructors",
      "Downsides and costs of exceptions",
      "noexcept",
      "std::move_if_noexcept",
      "Exception safety guarantees",
      "Alternatives: error codes and expected",
    ],
  ),
  cpp(
    "Input/Output & Streams",
    "input-output-and-streams",
    "Reading and writing text and files, formatting output, and the modern formatting library.",
    [
      "How I/O streams work",
      "Input with istream",
      "Formatting output with ostream",
      "String streams",
      "Stream states and validating input",
      "Reading and writing files",
      "Random access in files",
      "Binary file I/O",
      "std::format and std::print",
      "std::filesystem",
      "Fast I/O for competitive programming",
    ],
  ),
  cpp(
    "Modern C++ (11–23)",
    "modern-cpp-11-23",
    "What each standard added, the vocabulary types, concurrency, and where the language is heading next.",
    [
      "What C++11 changed",
      "C++14 additions",
      "C++17 additions",
      "C++20 additions",
      "C++23 additions",
      "std::variant and std::any",
      "Time with std::chrono",
      "Regular expressions with <regex>",
      "Threads: std::thread and std::jthread",
      "Mutexes and locks",
      "Condition variables",
      "Atomics and the memory model",
      "Futures, promises and std::async",
      "Coroutines",
      "Modules",
      "Looking ahead to C++26",
    ],
  ),
];

const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/\+/g, "p")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** A short, stable fingerprint of a string (FNV-1a), so ids stay unique when slugs collide. */
const fingerprint = (text: string) => {
  let hash = 0x811c9dc5;
  for (const char of text) hash = Math.imul(hash ^ char.codePointAt(0)!, 0x01000193);
  return (hash >>> 0).toString(36).padStart(7, "0").slice(-6);
};

/**
 * A subtopic's id, e.g. "cpp-oops/debugging/reading-compiler-error-messages-1x9k2a". The slug
 * keeps it readable; the fingerprint keeps "Overloading [] and ()" and "Overloading -> and *"
 * apart. Learners' read progress is stored against it, so renaming a live subtopic resets that
 * one checkbox.
 */
export const subtopicId = (guide: TopicGuide, name: string) =>
  `${guide.category}/${guide.slug}/${slugify(name).slice(0, 48)}-${fingerprint(name)}`;

/** A guide's subtopics with their ids, in study order. */
export const subtopicsOf = (guide: TopicGuide) =>
  guide.subtopics.map((name) => ({ id: subtopicId(guide, name), name }));

// A guide must point at a real syllabus topic, so a renamed topic fails the build — and its
// subtopic names double as React keys and progress ids, so they must be unique.
for (const guide of guides) {
  if (!getCategory(guide.category)?.topics.includes(guide.topic))
    throw new Error(`subtopics.ts: "${guide.topic}" isn't a topic of "${guide.category}" in categories.ts`);
  const ids = guide.subtopics.map((name) => subtopicId(guide, name));
  const repeated = guide.subtopics.find((_, i) => ids.indexOf(ids[i]) !== i);
  if (repeated) throw new Error(`subtopics.ts: "${repeated}" is listed twice under "${guide.topic}"`);
}

/** Every subtopic id on the site, so a progress update can't store anything else. */
export const allSubtopicIds = new Set(guides.flatMap((guide) => subtopicsOf(guide).map(({ id }) => id)));

export function getGuide(category: string, slug: string) {
  return guides.find((guide) => guide.category === category && guide.slug === slug);
}

/** The guide for a syllabus topic, if it has one. */
export function guideFor(category: string, topic: string) {
  return guides.find((guide) => guide.category === category && guide.topic === topic);
}

/** A category's guides, in syllabus order. */
export function guidesIn(category: string) {
  return guides.filter((guide) => guide.category === category);
}
