#!/usr/bin/env python3
"""Generates docs/review-track-cpp.md: every C++ subtopic mapped to the learncpp lessons
(or, where learncpp doesn't cover it, the reference docs) its page is checked against."""
import json, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://thelearninglogs.vercel.app"
L = "https://www.learncpp.com/cpp-tutorial/"
CPPREF = "https://en.cppreference.com/cpp/"

# number -> (title, url slug) for every learncpp lesson
LESSONS = {}
def add(chapter_rows):
    for num, title, slug in chapter_rows:
        LESSONS[num] = (title, L + slug + "/")

add([
 ("0.1","Introduction to these tutorials","introduction-to-these-tutorials"),
 ("0.2","Introduction to programs and programming languages","introduction-to-programming-languages"),
 ("0.3","Introduction to C/C++","introduction-to-cplusplus"),
 ("0.4","Introduction to C++ development","introduction-to-cpp-development"),
 ("0.5","Introduction to the compiler, linker, and libraries","introduction-to-the-compiler-linker-and-libraries"),
 ("0.6","Installing an Integrated Development Environment (IDE)","installing-an-integrated-development-environment-ide"),
 ("0.7","Compiling your first program","compiling-your-first-program"),
 ("0.8","A few common C++ problems","a-few-common-cpp-problems"),
 ("0.9","Configuring your compiler: Build configurations","configuring-your-compiler-build-configurations"),
 ("0.10","Configuring your compiler: Compiler extensions","configuring-your-compiler-compiler-extensions"),
 ("0.11","Configuring your compiler: Warning and error levels","configuring-your-compiler-warning-and-error-levels"),
 ("0.12","Configuring your compiler: Choosing a language standard","configuring-your-compiler-choosing-a-language-standard"),
 ("0.13","What language standard is my compiler using?","what-language-standard-is-my-compiler-using"),
 ("1.1","Statements and the structure of a program","statements-and-the-structure-of-a-program"),
 ("1.2","Comments","comments"),
 ("1.3","Introduction to objects and variables","introduction-to-objects-and-variables"),
 ("1.4","Variable assignment and initialization","variable-assignment-and-initialization"),
 ("1.5","Introduction to iostream: cout, cin, and endl","introduction-to-iostream-cout-cin-and-endl"),
 ("1.6","Uninitialized variables and undefined behavior","uninitialized-variables-and-undefined-behavior"),
 ("1.7","Keywords and naming identifiers","keywords-and-naming-identifiers"),
 ("1.8","Whitespace and basic formatting","whitespace-and-basic-formatting"),
 ("1.9","Introduction to literals and operators","introduction-to-literals-and-operators"),
 ("1.10","Introduction to expressions","introduction-to-expressions"),
 ("1.11","Developing your first program","developing-your-first-program"),
 ("1.x","Chapter 1 summary and quiz","chapter-1-summary-and-quiz"),
 ("2.1","Introduction to functions","introduction-to-functions"),
 ("2.2","Function return values (value-returning functions)","function-return-values-value-returning-functions"),
 ("2.3","Void functions (non-value returning functions)","void-functions-non-value-returning-functions"),
 ("2.4","Introduction to function parameters and arguments","introduction-to-function-parameters-and-arguments"),
 ("2.5","Introduction to local scope","introduction-to-local-scope"),
 ("2.6","Why functions are useful, and how to use them effectively","why-functions-are-useful-and-how-to-use-them-effectively"),
 ("2.7","Forward declarations and definitions","forward-declarations"),
 ("2.8","Programs with multiple code files","programs-with-multiple-code-files"),
 ("2.9","Naming collisions and an introduction to namespaces","naming-collisions-and-an-introduction-to-namespaces"),
 ("2.10","Introduction to the preprocessor","introduction-to-the-preprocessor"),
 ("2.11","Header files","header-files"),
 ("2.12","Header guards","header-guards"),
 ("2.13","How to design your first programs","how-to-design-your-first-programs"),
 ("2.x","Chapter 2 summary and quiz","chapter-2-summary-and-quiz"),
 ("3.1","Syntax and semantic errors","syntax-and-semantic-errors"),
 ("3.2","The debugging process","the-debugging-process"),
 ("3.3","A strategy for debugging","a-strategy-for-debugging"),
 ("3.4","Basic debugging tactics","basic-debugging-tactics"),
 ("3.5","More debugging tactics","more-debugging-tactics"),
 ("3.6","Using an integrated debugger: Stepping","using-an-integrated-debugger-stepping"),
 ("3.7","Using an integrated debugger: Running and breakpoints","using-an-integrated-debugger-running-and-breakpoints"),
 ("3.8","Using an integrated debugger: Watching variables","using-an-integrated-debugger-watching-variables"),
 ("3.9","Using an integrated debugger: The call stack","using-an-integrated-debugger-the-call-stack"),
 ("3.10","Finding issues before they become problems","finding-issues-before-they-become-problems"),
 ("3.x","Chapter 3 summary and quiz","chapter-3-summary-and-quiz"),
 ("4.1","Introduction to fundamental data types","introduction-to-fundamental-data-types"),
 ("4.2","Void","void"),
 ("4.3","Object sizes and the sizeof operator","object-sizes-and-the-sizeof-operator"),
 ("4.4","Signed integers","signed-integers"),
 ("4.5","Unsigned integers, and why to avoid them","unsigned-integers-and-why-to-avoid-them"),
 ("4.6","Fixed-width integers and size_t","fixed-width-integers-and-size-t"),
 ("4.7","Introduction to scientific notation","introduction-to-scientific-notation"),
 ("4.8","Floating point numbers","floating-point-numbers"),
 ("4.9","Boolean values","boolean-values"),
 ("4.10","Introduction to if statements","introduction-to-if-statements"),
 ("4.11","Chars","chars"),
 ("4.12","Introduction to type conversion and static_cast","introduction-to-type-conversion-and-static_cast"),
 ("4.x","Chapter 4 summary and quiz","chapter-4-summary-and-quiz"),
 ("5.1","Constant variables (named constants)","constant-variables-named-constants"),
 ("5.2","Literals","literals"),
 ("5.3","Numeral systems (decimal, binary, hexadecimal, and octal)","numeral-systems-decimal-binary-hexadecimal-and-octal"),
 ("5.4","The as-if rule and compile-time optimization","the-as-if-rule-and-compile-time-optimization"),
 ("5.5","Constant expressions","constant-expressions"),
 ("5.6","Constexpr variables","constexpr-variables"),
 ("5.7","Introduction to std::string","introduction-to-stdstring"),
 ("5.8","Introduction to std::string_view","introduction-to-stdstring_view"),
 ("5.9","std::string_view (part 2)","stdstring_view-part-2"),
 ("5.x","Chapter 5 summary and quiz","chapter-5-summary-and-quiz"),
 ("6.1","Operator precedence and associativity","operator-precedence-and-associativity"),
 ("6.2","Arithmetic operators","arithmetic-operators"),
 ("6.3","Remainder and Exponentiation","remainder-and-exponentiation"),
 ("6.4","Increment/decrement operators, and side effects","increment-decrement-operators-and-side-effects"),
 ("6.5","The comma operator","the-comma-operator"),
 ("6.6","The conditional operator","the-conditional-operator"),
 ("6.7","Relational operators and floating point comparisons","relational-operators-and-floating-point-comparisons"),
 ("6.8","Logical operators","logical-operators"),
 ("6.x","Chapter 6 summary and quiz","chapter-6-summary-and-quiz"),
 ("O.1","Bit flags and bit manipulation via std::bitset","bit-flags-and-bit-manipulation-via-stdbitset"),
 ("O.2","Bitwise operators","bitwise-operators"),
 ("O.3","Bit manipulation with bitwise operators and bit masks","bit-manipulation-with-bitwise-operators-and-bit-masks"),
 ("O.4","Converting integers between binary and decimal representation","converting-integers-between-binary-and-decimal-representation"),
 ("7.1","Compound statements (blocks)","compound-statements-blocks"),
 ("7.2","User-defined namespaces and the scope resolution operator","user-defined-namespaces-and-the-scope-resolution-operator"),
 ("7.3","Local variables","local-variables"),
 ("7.4","Introduction to global variables","introduction-to-global-variables"),
 ("7.5","Variable shadowing (name hiding)","variable-shadowing-name-hiding"),
 ("7.6","Internal linkage","internal-linkage"),
 ("7.7","External linkage and variable forward declarations","external-linkage-and-variable-forward-declarations"),
 ("7.8","Why (non-const) global variables are evil","why-non-const-global-variables-are-evil"),
 ("7.9","Inline functions and variables","inline-functions-and-variables"),
 ("7.10","Sharing global constants across multiple files (using inline variables)","sharing-global-constants-across-multiple-files-using-inline-variables"),
 ("7.11","Static local variables","static-local-variables"),
 ("7.12","Scope, duration, and linkage summary","scope-duration-and-linkage-summary"),
 ("7.13","Using declarations and using directives","using-declarations-and-using-directives"),
 ("7.14","Unnamed and inline namespaces","unnamed-and-inline-namespaces"),
 ("7.x","Chapter 7 summary and quiz","chapter-7-summary-and-quiz"),
 ("8.1","Control flow introduction","control-flow-introduction"),
 ("8.2","If statements and blocks","if-statements-and-blocks"),
 ("8.3","Common if statement problems","common-if-statement-problems"),
 ("8.4","Constexpr if statements","constexpr-if-statements"),
 ("8.5","Switch statement basics","switch-statement-basics"),
 ("8.6","Switch fallthrough and scoping","switch-fallthrough-and-scoping"),
 ("8.7","Goto statements","goto-statements"),
 ("8.8","Introduction to loops and while statements","introduction-to-loops-and-while-statements"),
 ("8.9","Do while statements","do-while-statements"),
 ("8.10","For statements","for-statements"),
 ("8.11","Break and continue","break-and-continue"),
 ("8.12","Halts (exiting your program early)","halts-exiting-your-program-early"),
 ("8.13","Introduction to random number generation","introduction-to-random-number-generation"),
 ("8.14","Generating random numbers using Mersenne Twister","generating-random-numbers-using-mersenne-twister"),
 ("8.15","Global random numbers (Random.h)","global-random-numbers-random-h"),
 ("8.x","Chapter 8 summary and quiz","chapter-8-summary-and-quiz"),
 ("9.1","Introduction to testing your code","introduction-to-testing-your-code"),
 ("9.2","Code coverage","code-coverage"),
 ("9.3","Common semantic errors in C++","common-semantic-errors-in-c"),
 ("9.4","Detecting and handling errors","detecting-and-handling-errors"),
 ("9.5","std::cin and handling invalid input","stdcin-and-handling-invalid-input"),
 ("9.6","Assert and static_assert","assert-and-static_assert"),
 ("9.x","Chapter 9 summary and quiz","chapter-9-summary-and-quiz"),
 ("10.1","Implicit type conversion","implicit-type-conversion"),
 ("10.2","Floating-point and integral promotion","floating-point-and-integral-promotion"),
 ("10.3","Numeric conversions","numeric-conversions"),
 ("10.4","Narrowing conversions, list initialization, and constexpr initializers","narrowing-conversions-list-initialization-and-constexpr-initializers"),
 ("10.5","Arithmetic conversions","arithmetic-conversions"),
 ("10.6","Explicit type conversion (casting) and static_cast","explicit-type-conversion-casting-and-static-cast"),
 ("10.7","Typedefs and type aliases","typedefs-and-type-aliases"),
 ("10.8","Type deduction for objects using the auto keyword","type-deduction-for-objects-using-the-auto-keyword"),
 ("10.9","Type deduction for functions","type-deduction-for-functions"),
 ("10.x","Chapter 10 summary and quiz","chapter-10-summary-and-quiz"),
 ("11.1","Introduction to function overloading","introduction-to-function-overloading"),
 ("11.2","Function overload differentiation","function-overload-differentiation"),
 ("11.3","Function overload resolution and ambiguous matches","function-overload-resolution-and-ambiguous-matches"),
 ("11.4","Deleting functions","deleting-functions"),
 ("11.5","Default arguments","default-arguments"),
 ("11.6","Function templates","function-templates"),
 ("11.7","Function template instantiation","function-template-instantiation"),
 ("11.8","Function templates with multiple template types","function-templates-with-multiple-template-types"),
 ("11.9","Non-type template parameters","non-type-template-parameters"),
 ("11.10","Using function templates in multiple files","using-function-templates-in-multiple-files"),
 ("11.x","Chapter 11 summary and quiz","chapter-11-summary-and-quiz"),
 ("F.1","Constexpr functions","constexpr-functions"),
 ("F.2","Constexpr functions (part 2)","constexpr-functions-part-2"),
 ("F.3","Constexpr functions (part 3) and consteval","constexpr-functions-part-3-and-consteval"),
 ("F.4","Constexpr functions (part 4)","constexpr-functions-part-4"),
 ("F.x","Chapter F summary and quiz","chapter-f-summary-and-quiz"),
 ("12.1","Introduction to compound data types","introduction-to-compound-data-types"),
 ("12.2","Value categories (lvalues and rvalues)","value-categories-lvalues-and-rvalues"),
 ("12.3","Lvalue references","lvalue-references"),
 ("12.4","Lvalue references to const","lvalue-references-to-const"),
 ("12.5","Pass by lvalue reference","pass-by-lvalue-reference"),
 ("12.6","Pass by const lvalue reference","pass-by-const-lvalue-reference"),
 ("12.7","Introduction to pointers","introduction-to-pointers"),
 ("12.8","Null pointers","null-pointers"),
 ("12.9","Pointers and const","pointers-and-const"),
 ("12.10","Pass by address","pass-by-address"),
 ("12.11","Pass by address (part 2)","pass-by-address-part-2"),
 ("12.12","Return by reference and return by address","return-by-reference-and-return-by-address"),
 ("12.13","In and out parameters","in-and-out-parameters"),
 ("12.14","Type deduction with pointers, references, and const","type-deduction-with-pointers-references-and-const"),
 ("12.15","std::optional","stdoptional"),
 ("12.x","Chapter 12 summary and quiz","chapter-12-summary-and-quiz"),
 ("13.1","Introduction to program-defined (user-defined) types","introduction-to-program-defined-user-defined-types"),
 ("13.2","Unscoped enumerations","unscoped-enumerations"),
 ("13.3","Unscoped enumerator integral conversions","unscoped-enumerator-integral-conversions"),
 ("13.4","Converting an enumeration to and from a string","converting-an-enumeration-to-and-from-a-string"),
 ("13.5","Introduction to overloading the I/O operators","introduction-to-overloading-the-i-o-operators"),
 ("13.6","Scoped enumerations (enum classes)","scoped-enumerations-enum-classes"),
 ("13.7","Introduction to structs, members, and member selection","introduction-to-structs-members-and-member-selection"),
 ("13.8","Struct aggregate initialization","struct-aggregate-initialization"),
 ("13.9","Default member initialization","default-member-initialization"),
 ("13.10","Passing and returning structs","passing-and-returning-structs"),
 ("13.11","Struct miscellany","struct-miscellany"),
 ("13.12","Member selection with pointers and references","member-selection-with-pointers-and-references"),
 ("13.13","Class templates","class-templates"),
 ("13.14","Class template argument deduction (CTAD) and deduction guides","class-template-argument-deduction-ctad-and-deduction-guides"),
 ("13.15","Alias templates","alias-templates"),
 ("13.x","Chapter 13 summary and quiz","chapter-13-summary-and-quiz"),
 ("13.y","Using a language reference","using-a-language-reference"),
 ("14.1","Introduction to object-oriented programming","introduction-to-object-oriented-programming"),
 ("14.2","Introduction to classes","introduction-to-classes"),
 ("14.3","Member functions","member-functions"),
 ("14.4","Const class objects and const member functions","const-class-objects-and-const-member-functions"),
 ("14.5","Public and private members and access specifiers","public-and-private-members-and-access-specifiers"),
 ("14.6","Access functions","access-functions"),
 ("14.7","Member functions returning references to data members","member-functions-returning-references-to-data-members"),
 ("14.8","The benefits of data hiding (encapsulation)","the-benefits-of-data-hiding-encapsulation"),
 ("14.9","Introduction to constructors","introduction-to-constructors"),
 ("14.10","Constructor member initializer lists","constructor-member-initializer-lists"),
 ("14.11","Default constructors and default arguments","default-constructors-and-default-arguments"),
 ("14.12","Delegating constructors","delegating-constructors"),
 ("14.13","Temporary class objects","temporary-class-objects"),
 ("14.14","Introduction to the copy constructor","introduction-to-the-copy-constructor"),
 ("14.15","Class initialization and copy elision","class-initialization-and-copy-elision"),
 ("14.16","Converting constructors and the explicit keyword","converting-constructors-and-the-explicit-keyword"),
 ("14.17","Constexpr aggregates and classes","constexpr-aggregates-and-classes"),
 ("14.x","Chapter 14 summary and quiz","chapter-14-summary-and-quiz"),
 ("15.1","The hidden “this” pointer and member function chaining","the-hidden-this-pointer-and-member-function-chaining"),
 ("15.2","Classes and header files","classes-and-header-files"),
 ("15.3","Nested types (member types)","nested-types-member-types"),
 ("15.4","Introduction to destructors","introduction-to-destructors"),
 ("15.5","Class templates with member functions","class-templates-with-member-functions"),
 ("15.6","Static member variables","static-member-variables"),
 ("15.7","Static member functions","static-member-functions"),
 ("15.8","Friend non-member functions","friend-non-member-functions"),
 ("15.9","Friend classes and friend member functions","friend-classes-and-friend-member-functions"),
 ("15.10","Ref qualifiers","ref-qualifiers"),
 ("15.x","Chapter 15 summary and quiz","chapter-15-summary-and-quiz"),
 ("16.1","Introduction to containers and arrays","introduction-to-containers-and-arrays"),
 ("16.2","Introduction to std::vector and list constructors","introduction-to-stdvector-and-list-constructors"),
 ("16.3","std::vector and the unsigned length and subscript problem","stdvector-and-the-unsigned-length-and-subscript-problem"),
 ("16.4","Passing std::vector","passing-stdvector"),
 ("16.5","Returning std::vector, and an introduction to move semantics","returning-stdvector-and-an-introduction-to-move-semantics"),
 ("16.6","Arrays and loops","arrays-and-loops"),
 ("16.7","Arrays, loops, and sign challenge solutions","arrays-loops-and-sign-challenge-solutions"),
 ("16.8","Range-based for loops (for-each)","range-based-for-loops-for-each"),
 ("16.9","Array indexing and length using enumerators","array-indexing-and-length-using-enumerators"),
 ("16.10","std::vector resizing and capacity","stdvector-resizing-and-capacity"),
 ("16.11","std::vector and stack behavior","stdvector-and-stack-behavior"),
 ("16.12","std::vector<bool>","stdvector-bool"),
 ("16.x","Chapter 16 summary and quiz","chapter-16-summary-and-quiz"),
 ("17.1","Introduction to std::array","introduction-to-stdarray"),
 ("17.2","std::array length and indexing","stdarray-length-and-indexing"),
 ("17.3","Passing and returning std::array","passing-and-returning-stdarray"),
 ("17.4","std::array of class types, and brace elision","stdarray-of-class-types-and-brace-elision"),
 ("17.5","Arrays of references via std::reference_wrapper","arrays-of-references-via-stdreference_wrapper"),
 ("17.6","std::array and enumerations","stdarray-and-enumerations"),
 ("17.7","Introduction to C-style arrays","introduction-to-c-style-arrays"),
 ("17.8","C-style array decay","c-style-array-decay"),
 ("17.9","Pointer arithmetic and subscripting","pointer-arithmetic-and-subscripting"),
 ("17.10","C-style strings","c-style-strings"),
 ("17.11","C-style string symbolic constants","c-style-string-symbolic-constants"),
 ("17.12","Multidimensional C-style Arrays","multidimensional-c-style-arrays"),
 ("17.13","Multidimensional std::array","multidimensional-stdarray"),
 ("17.x","Chapter 17 summary and quiz","chapter-17-summary-and-quiz"),
 ("18.1","Sorting an array using selection sort","sorting-an-array-using-selection-sort"),
 ("18.2","Introduction to iterators","introduction-to-iterators"),
 ("18.3","Introduction to standard library algorithms","introduction-to-standard-library-algorithms"),
 ("18.4","Timing your code","timing-your-code"),
 ("19.1","Dynamic memory allocation with new and delete","dynamic-memory-allocation-with-new-and-delete"),
 ("19.2","Dynamically allocating arrays","dynamically-allocating-arrays"),
 ("19.3","Destructors","destructors"),
 ("19.4","Pointers to pointers and dynamic multidimensional arrays","pointers-to-pointers"),
 ("19.5","Void pointers","void-pointers"),
 ("20.1","Function Pointers","function-pointers"),
 ("20.2","The stack and the heap","the-stack-and-the-heap"),
 ("20.3","Recursion","recursion"),
 ("20.4","Command line arguments","command-line-arguments"),
 ("20.5","Ellipsis (and why to avoid them)","ellipsis-and-why-to-avoid-them"),
 ("20.6","Introduction to lambdas (anonymous functions)","introduction-to-lambdas-anonymous-functions"),
 ("20.7","Lambda captures","lambda-captures"),
 ("20.x","Chapter 20 summary and quiz","chapter-20-summary-and-quiz"),
 ("21.1","Introduction to operator overloading","introduction-to-operator-overloading"),
 ("21.2","Overloading the arithmetic operators using friend functions","overloading-the-arithmetic-operators-using-friend-functions"),
 ("21.3","Overloading operators using normal functions","overloading-operators-using-normal-functions"),
 ("21.4","Overloading the I/O operators","overloading-the-io-operators"),
 ("21.5","Overloading operators using member functions","overloading-operators-using-member-functions"),
 ("21.6","Overloading unary operators +, -, and !","overloading-unary-operators"),
 ("21.7","Overloading the comparison operators","overloading-the-comparison-operators"),
 ("21.8","Overloading the increment and decrement operators","overloading-the-increment-and-decrement-operators"),
 ("21.9","Overloading the subscript operator","overloading-the-subscript-operator"),
 ("21.10","Overloading the parenthesis operator","overloading-the-parenthesis-operator"),
 ("21.11","Overloading typecasts","overloading-typecasts"),
 ("21.12","Overloading the assignment operator","overloading-the-assignment-operator"),
 ("21.13","Shallow vs. deep copying","shallow-vs-deep-copying"),
 ("21.14","Overloading operators and function templates","overloading-operators-and-function-templates"),
 ("21.x","Chapter 21 summary and quiz","chapter-21-summary-and-quiz"),
 ("21.y","Chapter 21 project","chapter-21-project"),
 ("22.1","Introduction to smart pointers and move semantics","introduction-to-smart-pointers-move-semantics"),
 ("22.2","R-value references","rvalue-references"),
 ("22.3","Move constructors and move assignment","move-constructors-and-move-assignment"),
 ("22.4","std::move","stdmove"),
 ("22.5","std::unique_ptr","stdunique_ptr"),
 ("22.6","std::shared_ptr","stdshared_ptr"),
 ("22.7","Circular dependency issues with std::shared_ptr, and std::weak_ptr","circular-dependency-issues-with-stdshared_ptr-and-stdweak_ptr"),
 ("22.x","Chapter 22 summary and quiz","chapter-22-summary-and-quiz"),
 ("23.1","Object relationships","object-relationships"),
 ("23.2","Composition","composition"),
 ("23.3","Aggregation","aggregation"),
 ("23.4","Association","association"),
 ("23.5","Dependencies","dependencies"),
 ("23.6","Container classes","container-classes"),
 ("23.7","std::initializer_list","stdinitializer_list"),
 ("23.x","Chapter 23 summary and quiz","chapter-23-summary-and-quiz"),
 ("24.1","Introduction to inheritance","introduction-to-inheritance"),
 ("24.2","Basic inheritance in C++","basic-inheritance-in-c"),
 ("24.3","Order of construction of derived classes","order-of-construction-of-derived-classes"),
 ("24.4","Constructors and initialization of derived classes","constructors-and-initialization-of-derived-classes"),
 ("24.5","Inheritance and access specifiers","inheritance-and-access-specifiers"),
 ("24.6","Adding new functionality to a derived class","adding-new-functionality-to-a-derived-class"),
 ("24.7","Calling inherited functions and overriding behavior","calling-inherited-functions-and-overriding-behavior"),
 ("24.8","Hiding inherited functionality","hiding-inherited-functionality"),
 ("24.9","Multiple inheritance","multiple-inheritance"),
 ("24.x","Chapter 24 summary and quiz","chapter-24-summary-and-quiz"),
 ("25.1","Pointers and references to the base class of derived objects","pointers-and-references-to-the-base-class-of-derived-objects"),
 ("25.2","Virtual functions and polymorphism","virtual-functions"),
 ("25.3","The override and final specifiers, and covariant return types","the-override-and-final-specifiers-and-covariant-return-types"),
 ("25.4","Virtual destructors, virtual assignment, and overriding virtualization","virtual-destructors-virtual-assignment-and-overriding-virtualization"),
 ("25.5","Early binding and late binding","early-binding-and-late-binding"),
 ("25.6","The virtual table","the-virtual-table"),
 ("25.7","Pure virtual functions, abstract base classes, and interface classes","pure-virtual-functions-abstract-base-classes-and-interface-classes"),
 ("25.8","Virtual base classes","virtual-base-classes"),
 ("25.9","Object slicing","object-slicing"),
 ("25.10","Dynamic casting","dynamic-casting"),
 ("25.11","Printing inherited classes using operator<<","printing-inherited-classes-using-operator"),
 ("25.x","Chapter 25 summary and quiz","chapter-25-summary-and-quiz"),
 ("26.1","Template classes","template-classes"),
 ("26.2","Template non-type parameters","template-non-type-parameters"),
 ("26.3","Function template specialization","function-template-specialization"),
 ("26.4","Class template specialization","class-template-specialization"),
 ("26.5","Partial template specialization","partial-template-specialization"),
 ("26.6","Partial template specialization for pointers","partial-template-specialization-for-pointers"),
 ("26.x","Chapter 26 summary and quiz","chapter-26-summary-and-quiz"),
 ("27.1","The need for exceptions","the-need-for-exceptions"),
 ("27.2","Basic exception handling","basic-exception-handling"),
 ("27.3","Exceptions, functions, and stack unwinding","exceptions-functions-and-stack-unwinding"),
 ("27.4","Uncaught exceptions and catch-all handlers","uncaught-exceptions-catch-all-handlers"),
 ("27.5","Exceptions, classes, and inheritance","exceptions-classes-and-inheritance"),
 ("27.6","Rethrowing exceptions","rethrowing-exceptions"),
 ("27.7","Function try blocks","function-try-blocks"),
 ("27.8","Exception dangers and downsides","exception-dangers-and-downsides"),
 ("27.9","Exception specifications and noexcept","exception-specifications-and-noexcept"),
 ("27.10","std::move_if_noexcept","stdmove_if_noexcept"),
 ("27.x","Chapter 27 summary and quiz","chapter-27-summary-and-quiz"),
 ("28.1","Input and output (I/O) streams","input-and-output-io-streams"),
 ("28.2","Input with istream","input-with-istream"),
 ("28.3","Output with ostream and ios","output-with-ostream-and-ios"),
 ("28.4","Stream classes for strings","stream-classes-for-strings"),
 ("28.5","Stream states and input validation","stream-states-and-input-validation"),
 ("28.6","Basic file I/O","basic-file-io"),
 ("28.7","Random file I/O","random-file-io"),
 ("A.1","Static and dynamic libraries","a1-static-and-dynamic-libraries"),
 ("A.2","Using libraries with Visual Studio","a2-using-libraries-with-visual-studio-2005-express"),
 ("A.3","Using libraries with Code::Blocks","a3-using-libraries-with-codeblocks"),
 ("A.4","C++ FAQ","cpp-faq"),
 ("B.1","Introduction to C++11","introduction-to-c11"),
 ("B.2","Introduction to C++14","introduction-to-c14"),
 ("B.3","Introduction to C++17","introduction-to-c17"),
 ("B.4","Introduction to C++20","introduction-to-c20"),
 ("B.5","Introduction to C++23","introduction-to-c23"),
 ("D.21.1","The Standard Library (archived)","the-standard-library"),
 ("D.21.2","STL containers overview (archived)","stl-containers-overview"),
 ("D.21.3","STL iterators overview (archived)","stl-iterators-overview"),
 ("D.21.4","STL algorithms overview (archived)","stl-algorithms-overview"),
 ("D.22.1","std::string and std::wstring (archived)","stdstring-and-stdwstring"),
 ("D.22.2","std::string construction and destruction (archived)","stdstring-construction-and-destruction"),
 ("D.22.3","std::string length and capacity (archived)","stdstring-length-and-capacity"),
 ("D.22.4","std::string character access and conversion to C-style arrays (archived)","stdstring-character-access-and-conversion-to-c-style-arrays"),
 ("D.22.5","std::string assignment and swapping (archived)","stdstring-assignment-and-swapping"),
 ("D.22.6","std::string appending (archived)","stdstring-appending"),
 ("D.22.7","std::string inserting (archived)","stdstring-inserting"),
])

R = lambda path: CPPREF + path  # a cppreference page

# subtopic -> learncpp lessons it covers. "rel" = related learncpp lessons when learncpp doesn't
# cover the subtopic itself; "ext" = (label, url) reference docs to verify our-own material against.
def M(lessons="", rel="", ext=()):
    return {"lessons": lessons.split(), "rel": rel.split(), "ext": list(ext)}

MAP = {
 # 01 C++ Basics & Functions
 "What C++ is": M("0.1 0.2 0.3"),
 "From source code to a running program": M("0.4 0.5 0.7 0.8"),
 "Setting up the compiler": M("0.6 0.9 0.10 0.11 0.12 0.13 0.7"),
 "Compiling from the command line": M(rel="0.5 0.7 0.9 0.11 0.12 2.8 A.1", ext=[("GCC manual: Invoking GCC","https://gcc.gnu.org/onlinedocs/gcc/Invoking-GCC.html"),("GCC: Overall options (-c, -o, -E, -S)","https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html")]),
 "Statements and program structure": M("1.1 1.2"),
 "Variables and initialization": M("1.3 1.4"),
 "Console input and output": M("1.5"),
 "Uninitialized variables and undefined behavior": M("1.6"),
 "Identifiers, keywords and formatting": M("1.7 1.8"),
 "Literals, operators and expressions": M("1.9 1.10"),
 "Functions, return values and parameters": M("2.1 2.2 2.3 2.4"),
 "Local scope and using functions well": M("2.5 2.6"),
 "Forward declarations and multiple files": M("2.7 2.8"),
 "Namespaces": M("2.9"),
 "Preprocessor, headers and header guards": M("2.10 2.11 2.12"),
 "Static and dynamic libraries": M("A.1 A.2 A.3"),
 "Build systems: Make and CMake": M(rel="A.1", ext=[("GNU Make manual","https://www.gnu.org/software/make/manual/make.html"),("CMake tutorial","https://cmake.org/cmake/help/latest/guide/tutorial/index.html")]),
 "Designing your first programs": M("1.11 2.13 1.x 2.x"),
 # 02 Debugging
 "Syntax errors vs semantic errors": M("3.1"),
 "Reading compiler error messages": M(rel="3.1 0.11", ext=[("GCC: Diagnostic message formatting","https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Message-Formatting-Options.html")]),
 "A systematic debugging process": M("3.2 3.3"),
 "Print debugging and logging": M("3.4 3.5"),
 "Stepping through code": M("3.6"),
 "Breakpoints and run-to-cursor": M("3.7"),
 "Watching variables": M("3.8"),
 "Reading the call stack": M("3.9"),
 "Debugging with gdb and lldb": M(rel="3.6 3.7 3.8 3.9", ext=[("GDB manual","https://sourceware.org/gdb/current/onlinedocs/gdb.html/"),("LLDB tutorial","https://lldb.llvm.org/use/tutorial.html")]),
 "AddressSanitizer and UBSan": M(rel="1.6", ext=[("Clang: AddressSanitizer","https://clang.llvm.org/docs/AddressSanitizer.html"),("Clang: UndefinedBehaviorSanitizer","https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html")]),
 "Finding memory leaks with Valgrind": M(rel="19.1", ext=[("Valgrind quick start","https://valgrind.org/docs/manual/quick-start.html")]),
 "Static analysis with clang-tidy": M(rel="3.10", ext=[("clang-tidy docs","https://clang.llvm.org/extra/clang-tidy/")]),
 "Defensive habits that prevent bugs": M("3.10 3.x"),
 # 03 Data Types, Constants & Strings
 "The fundamental types at a glance": M("4.1"),
 "void": M("4.2"),
 "Object sizes and sizeof": M("4.3"),
 "Signed integers and overflow": M("4.4"),
 "Unsigned integers and their traps": M("4.5"),
 "Fixed-width integers and size_t": M("4.6"),
 "Type limits with std::numeric_limits": M(rel="4.3 4.4", ext=[("cppreference: std::numeric_limits",R("types/numeric_limits"))]),
 "Scientific notation": M("4.7"),
 "Floating-point numbers and precision": M("4.8"),
 "Booleans and a first look at if": M("4.9 4.10"),
 "Characters and char": M("4.11"),
 "Converting types with static_cast": M("4.12 4.x"),
 "Const variables": M("5.1"),
 "Literals and literal suffixes": M("5.2"),
 "Binary, octal and hexadecimal": M("5.3"),
 "The as-if rule and optimization": M("5.4"),
 "Constant expressions": M("5.5"),
 "constexpr variables": M("5.6"),
 "std::string basics": M("5.7"),
 "Working with std::string": M("D.22.1 D.22.2 D.22.3 D.22.4 D.22.5 D.22.6 D.22.7", ext=[("cppreference: std::basic_string",R("string/basic_string"))]),
 "std::string_view": M("5.8 5.9 5.x"),
 "Converting between strings and numbers": M(rel="5.7", ext=[("cppreference: std::stoi / std::stol",R("string/basic_string/stol")),("cppreference: std::to_string",R("string/basic_string/to_string")),("cppreference: std::from_chars",R("utility/from_chars"))]),
 "Character handling with <cctype>": M(rel="4.11", ext=[("cppreference: <cctype>",R("header/cctype"))]),
 "Unicode and wide character types": M(rel="4.11 D.22.1", ext=[("cppreference: fundamental types (character types)",R("language/types"))]),
 # 04 Operators & Bit Manipulation
 "Precedence and associativity": M("6.1"),
 "Arithmetic and integer division": M("6.2"),
 "Remainder and exponentiation": M("6.3"),
 "Increment, decrement and side effects": M("6.4"),
 "Order of evaluation pitfalls": M(rel="6.1 6.4", ext=[("cppreference: order of evaluation",R("language/eval_order"))]),
 "The comma operator": M("6.5"),
 "The conditional operator ?:": M("6.6"),
 "Comparisons and floating-point pitfalls": M("6.7"),
 "Logical operators and short-circuiting": M("6.8 6.x"),
 "Bit flags with std::bitset": M("O.1"),
 "Bitwise operators": M("O.2"),
 "Bit masks": M("O.3"),
 "Binary to decimal and back": M("O.4"),
 "The <bit> header (C++20)": M(rel="O.1 O.2 O.3", ext=[("cppreference: <bit>",R("header/bit"))]),
 # 05 Scope, Duration & Linkage
 "Blocks and nested scopes": M("7.1"),
 "User-defined namespaces": M("7.2"),
 "Local variables: scope and lifetime": M("7.3"),
 "Global variables": M("7.4"),
 "Variable shadowing": M("7.5"),
 "Internal linkage": M("7.6"),
 "External linkage and extern": M("7.7"),
 "Why mutable globals are risky": M("7.8"),
 "The One Definition Rule": M(rel="2.7 7.9", ext=[("cppreference: definitions and the ODR",R("language/definition"))]),
 "Inline functions and variables": M("7.9"),
 "Sharing constants across files": M("7.10"),
 "Static local variables": M("7.11"),
 "Static initialization order": M(rel="7.8", ext=[("cppreference: static initialization order fiasco",R("language/siof"))]),
 "thread_local variables": M(rel="7.12", ext=[("cppreference: storage duration",R("language/storage_duration"))]),
 "using declarations and directives": M("7.13"),
 "Unnamed and inline namespaces": M("7.14"),
 'Name mangling and extern "C"': M(rel="7.7", ext=[("cppreference: language linkage",R("language/language_linkage"))]),
 "Scope, duration and linkage recap": M("7.12 7.x"),
 # 06 Control Flow & Error Handling
 "How control flow works": M("8.1"),
 "if statements and blocks": M("8.2"),
 "Common if-statement mistakes": M("8.3"),
 "if and switch with initializers": M(rel="8.2 8.5", ext=[("cppreference: if statement",R("language/if")),("cppreference: switch statement",R("language/switch"))]),
 "if constexpr": M("8.4"),
 "switch statements": M("8.5"),
 "Fallthrough and scope in switch": M("8.6"),
 "goto, and why to avoid it": M("8.7"),
 "while loops": M("8.8"),
 "do-while loops": M("8.9"),
 "for loops": M("8.10"),
 "break and continue": M("8.11"),
 "Exiting early: exit, abort, terminate": M("8.12"),
 "Random number generation": M("8.13"),
 "The Mersenne Twister": M("8.14"),
 "A reusable random number helper": M("8.15 8.x"),
 "Testing your code": M("9.1"),
 "Code coverage": M("9.2"),
 "Common semantic errors": M("9.3"),
 "Detecting and handling errors": M("9.4"),
 "Handling invalid input from std::cin": M("9.5"),
 "assert and static_assert": M("9.6 9.x"),
 "Unit testing with GoogleTest and Catch2": M(rel="9.1", ext=[("GoogleTest primer","https://google.github.io/googletest/primer.html"),("Catch2 tutorial","https://github.com/catchorg/Catch2/blob/devel/docs/tutorial.md")]),
 # 07 Type Conversion & Deduction
 "Implicit type conversion": M("10.1"),
 "Numeric promotions": M("10.2"),
 "Numeric conversions": M("10.3"),
 "Narrowing and brace initialization": M("10.4"),
 "The usual arithmetic conversions": M("10.5"),
 "Explicit casts with static_cast": M("10.6"),
 "const_cast and reinterpret_cast": M(rel="10.6", ext=[("cppreference: const_cast",R("language/const_cast")),("cppreference: reinterpret_cast",R("language/reinterpret_cast"))]),
 "Why to avoid C-style casts": M("10.6", ext=[("cppreference: explicit type conversion",R("language/explicit_cast"))]),
 "typedefs and type aliases": M("10.7"),
 "auto for variables": M("10.8"),
 "auto and trailing return types": M("10.9 10.x"),
 "decltype and decltype(auto)": M(rel="10.8 10.9", ext=[("cppreference: decltype",R("language/decltype"))]),
 # 08 Overloading, Templates & constexpr
 "Function overloading": M("11.1"),
 "How overloads are told apart": M("11.2"),
 "Overload resolution and ambiguity": M("11.3"),
 "Deleted functions": M("11.4"),
 "Default arguments": M("11.5"),
 "Function templates": M("11.6"),
 "How templates are instantiated": M("11.7"),
 "Templates with several type parameters": M("11.8"),
 "Abbreviated templates with auto": M("11.8"),
 "Non-type template parameters": M("11.9"),
 "Templates across multiple files": M("11.10 11.x"),
 "constexpr functions": M("F.1"),
 "When constexpr runs at compile time": M("F.2 F.4"),
 "consteval functions": M("F.3 F.x"),
 "constinit": M(rel="F.3 5.6", ext=[("cppreference: constinit",R("language/constinit"))]),
 # 09 References & Pointers
 "Compound types": M("12.1"),
 "Value categories: lvalues and rvalues": M("12.2"),
 "Lvalue references": M("12.3"),
 "References to const": M("12.4"),
 "Pass by reference": M("12.5"),
 "Pass by const reference": M("12.6"),
 "Pointers": M("12.7"),
 "Null pointers and nullptr": M("12.8"),
 "Pointers and const": M("12.9"),
 "Pass by address": M("12.10 12.11"),
 "Return by reference or address": M("12.12"),
 "In and out parameters": M("12.13"),
 "Dangling pointers and references": M(rel="12.3 12.12", ext=[("cppreference: references (dangling references)",R("language/reference"))]),
 "Pointers vs references": M(rel="12.7 12.10", ext=[("cppreference: pointer declaration",R("language/pointer"))]),
 "auto with references and pointers": M("12.14"),
 "std::optional": M("12.15 12.x"),
 # 10 Enums & Structs
 "Program-defined types": M("13.1"),
 "Unscoped enumerations": M("13.2"),
 "Enums and integer conversions": M("13.3"),
 "Enums to and from strings": M("13.4"),
 "A first look at overloading << and >>": M("13.5"),
 "Scoped enums (enum class)": M("13.6"),
 "Structs and member access": M("13.7"),
 "Aggregate initialization": M("13.8"),
 "Designated initializers": M("13.8", ext=[("cppreference: aggregate initialization (designated initializers)",R("language/aggregate_initialization"))]),
 "Default member initializers": M("13.9"),
 "Passing and returning structs": M("13.10"),
 "Padding and alignment": M("13.11", ext=[("cppreference: object alignment",R("language/object"))]),
 "Member access through pointers": M("13.12"),
 "Structured bindings": M(rel="13.10", ext=[("cppreference: structured bindings",R("language/structured_binding"))]),
 "std::pair and std::tuple": M(rel="13.13", ext=[("cppreference: std::pair",R("utility/pair")),("cppreference: std::tuple",R("utility/tuple"))]),
 "Unions": M(ext=[("cppreference: union declaration",R("language/union"))]),
 "A first look at class templates": M("13.13"),
 "CTAD and deduction guides": M("13.14"),
 "Alias templates": M("13.15 13.x"),
 "Reading the language reference": M("13.y"),
 # 11 Classes & Objects (OOPS 1)
 "What object-oriented programming is": M("14.1"),
 "Classes vs structs": M("14.2"),
 "Member functions": M("14.3"),
 "const member functions": M("14.4"),
 "mutable members": M(rel="14.4", ext=[("cppreference: cv and mutable specifiers",R("language/cv"))]),
 "Access specifiers": M("14.5"),
 "Getters and setters": M("14.6"),
 "Returning references to members": M("14.7"),
 "Encapsulation and data hiding": M("14.8"),
 "Constructors": M("14.9"),
 "Member initializer lists": M("14.10"),
 "Default constructors": M("14.11"),
 "Delegating constructors": M("14.12"),
 "Temporary objects": M("14.13"),
 "Copy constructors": M("14.14"),
 "Copy elision and RVO": M("14.15"),
 "Converting constructors and explicit": M("14.16"),
 "= default and = delete": M(rel="14.11 14.14 11.4", ext=[("cppreference: function definition (defaulted and deleted)",R("language/function"))]),
 "constexpr classes": M("14.17 14.x"),
 "The this pointer and chaining": M("15.1"),
 "Classes in header and source files": M("15.2"),
 "Nested types": M("15.3"),
 "Destructors": M("15.4"),
 "Member functions of class templates": M("15.5"),
 "Static member variables": M("15.6"),
 "Static member functions": M("15.7"),
 "Friend functions": M("15.8"),
 "Friend classes": M("15.9"),
 "Ref qualifiers": M("15.10 15.x"),
 # 12 std::vector & Arrays
 "Containers and arrays": M("16.1"),
 "std::vector basics": M("16.2"),
 "Signed vs unsigned indices": M("16.3 16.7"),
 "Passing std::vector": M("16.4"),
 "Returning vectors and moving": M("16.5"),
 "Looping over arrays": M("16.6 16.7"),
 "Range-based for loops": M("16.8"),
 "Indexing with enumerators": M("16.9"),
 "Size, capacity and how vector grows": M("16.10"),
 "push_back vs emplace_back": M("16.11", ext=[("cppreference: std::vector::emplace_back",R("container/vector/emplace_back"))]),
 "Using a vector as a stack": M("16.11"),
 "std::vector<bool>": M("16.12 16.x"),
 "std::array basics": M("17.1"),
 "std::array length and indexing": M("17.2"),
 "Passing and returning std::array": M("17.3"),
 "std::array of class types": M("17.4"),
 "std::reference_wrapper": M("17.5"),
 "std::array with enumerations": M("17.6"),
 "C-style arrays": M("17.7"),
 "Array decay": M("17.8"),
 "Pointer arithmetic": M("17.9"),
 "C-style strings": M("17.10 17.11"),
 "Multidimensional arrays": M("17.12"),
 "Multidimensional std::array": M("17.13 17.x"),
 "std::span": M(rel="17.8", ext=[("cppreference: std::span",R("container/span"))]),
 # 13 STL Containers, Iterators & Algorithms
 "The STL at a glance": M("D.21.1 D.21.2"),
 "Sorting by hand: selection sort": M("18.1"),
 "Iterators": M("18.2 D.21.3"),
 "Iterator categories": M(rel="D.21.3", ext=[("cppreference: iterator library",R("iterator"))]),
 "Iterator invalidation": M(rel="18.2", ext=[("cppreference: containers library (iterator invalidation)",R("container"))]),
 "deque, list and forward_list": M(rel="D.21.2", ext=[("cppreference: std::deque",R("container/deque")),("cppreference: std::list",R("container/list")),("cppreference: std::forward_list",R("container/forward_list"))]),
 "stack, queue and priority_queue": M(rel="D.21.2 16.11", ext=[("cppreference: std::stack",R("container/stack")),("cppreference: std::queue",R("container/queue")),("cppreference: std::priority_queue",R("container/priority_queue"))]),
 "set and multiset": M(rel="D.21.2", ext=[("cppreference: std::set",R("container/set")),("cppreference: std::multiset",R("container/multiset"))]),
 "map and multimap": M(rel="D.21.2", ext=[("cppreference: std::map",R("container/map")),("cppreference: std::multimap",R("container/multimap"))]),
 "unordered_set and unordered_map": M(rel="D.21.2", ext=[("cppreference: std::unordered_set",R("container/unordered_set")),("cppreference: std::unordered_map",R("container/unordered_map"))]),
 "Custom comparators and hashes": M(rel="18.3", ext=[("cppreference: Compare requirement",R("named_req/Compare")),("cppreference: std::hash",R("utility/hash"))]),
 "Choosing the right container": M(rel="D.21.2", ext=[("cppreference: containers library",R("container"))]),
 "Standard algorithms": M("18.3 D.21.4"),
 "Sorting and searching algorithms": M(rel="18.3", ext=[("cppreference: std::sort",R("algorithm/sort")),("cppreference: std::lower_bound",R("algorithm/lower_bound"))]),
 "Modifying algorithms and erase-remove": M(rel="18.3", ext=[("cppreference: std::remove",R("algorithm/remove")),("cppreference: std::erase / std::erase_if (vector)",R("container/vector/erase2"))]),
 "Numeric algorithms": M(rel="18.3", ext=[("cppreference: <numeric>",R("header/numeric"))]),
 "Heap and partition algorithms": M(rel="18.3", ext=[("cppreference: std::make_heap",R("algorithm/make_heap")),("cppreference: std::partition",R("algorithm/partition")),("cppreference: std::nth_element",R("algorithm/nth_element"))]),
 "Ranges and views (C++20)": M(rel="B.4", ext=[("cppreference: ranges library",R("ranges"))]),
 "Timing your code": M("18.4"),
 # 14 Dynamic Allocation
 "The stack and the heap": M("20.2"),
 "new and delete": M("19.1"),
 "Dynamic arrays with new[]": M("19.2"),
 "Destructors and cleanup": M("19.3"),
 "Pointers to pointers": M("19.4"),
 "Dynamic multidimensional arrays": M("19.4"),
 "void pointers": M("19.5"),
 "Leaks, dangling and double deletes": M(rel="19.1", ext=[("Clang: AddressSanitizer","https://clang.llvm.org/docs/AddressSanitizer.html")]),
 "new/delete vs malloc/free": M(rel="19.1", ext=[("cppreference: std::malloc",R("memory/c/malloc"))]),
 "Placement new": M(ext=[("cppreference: new expression (placement new)",R("language/new"))]),
 "Overloading new and delete": M(ext=[("cppreference: operator new",R("memory/new/operator_new"))]),
 "Allocators and memory pools": M(ext=[("cppreference: Allocator requirement",R("named_req/Allocator")),("cppreference: std::pmr::polymorphic_allocator",R("memory/polymorphic_allocator"))]),
 # 15 Function Pointers, Recursion & Lambdas
 "Function pointers": M("20.1"),
 "Callbacks and std::function": M("20.1", ext=[("cppreference: std::function",R("utility/functional/function"))]),
 "Recursion": M("20.3"),
 "Command-line arguments": M("20.4"),
 "Ellipsis and why to avoid it": M("20.5"),
 "Lambdas": M("20.6"),
 "Lambda captures": M("20.7 20.x"),
 "Generic lambdas": M("20.6"),
 "Lambdas with STL algorithms": M("20.6 18.3"),
 "std::invoke and std::bind": M(ext=[("cppreference: std::invoke",R("utility/functional/invoke")),("cppreference: std::bind",R("utility/functional/bind"))]),
 # 16 Operator Overloading (OOPS 2)
 "Operator overloading basics": M("21.1"),
 "Overloading with friend functions": M("21.2"),
 "Overloading with normal functions": M("21.3"),
 "Overloading << and >>": M("21.4"),
 "Overloading with member functions": M("21.5"),
 "Unary operators": M("21.6"),
 "Comparison operators": M("21.7"),
 "The spaceship operator <=>": M(rel="21.7 B.4", ext=[("cppreference: default comparisons",R("language/default_comparisons"))]),
 "Increment and decrement": M("21.8"),
 "The subscript operator []": M("21.9"),
 "The call operator () and functors": M("21.10"),
 "Conversion operators": M("21.11"),
 "Overloading -> and *": M(ext=[("cppreference: operator overloading",R("language/operators"))]),
 "The assignment operator": M("21.12"),
 "Shallow vs deep copy": M("21.13"),
 "The copy-and-swap idiom": M(rel="21.12", ext=[("cppreference: copy assignment operator",R("language/copy_assignment"))]),
 "Operators and function templates": M("21.14"),
 "Rules and good practice": M("21.x", rel="21.1", ext=[("cppreference: operator overloading",R("language/operators"))]),
 "Project: a fully overloaded class": M("21.y"),
 # 17 Move Semantics & Smart Pointers
 "Why smart pointers and moves exist": M("22.1"),
 "RAII": M(rel="19.3 22.1", ext=[("cppreference: RAII",R("language/raii"))]),
 "Rvalue references": M("22.2"),
 "Move constructor and move assignment": M("22.3"),
 "std::move": M("22.4"),
 "The rule of three, five and zero": M(rel="21.12 22.3", ext=[("cppreference: the rule of three/five/zero",R("language/rule_of_three"))]),
 "std::unique_ptr": M("22.5"),
 "std::shared_ptr": M("22.6"),
 "make_unique and make_shared": M("22.5 22.6"),
 "Custom deleters": M(ext=[("cppreference: std::unique_ptr",R("memory/unique_ptr"))]),
 "std::weak_ptr and reference cycles": M("22.7 22.x"),
 "Forwarding references": M(rel="22.2", ext=[("cppreference: references (forwarding references)",R("language/reference"))]),
 "Perfect forwarding with std::forward": M(rel="22.4", ext=[("cppreference: std::forward",R("utility/forward"))]),
 # 18 Object Relationships (OOPS 3)
 "Kinds of object relationships": M("23.1"),
 "Composition": M("23.2"),
 "Aggregation": M("23.3"),
 "Association": M("23.4"),
 "Dependencies": M("23.5"),
 "Ownership and lifetimes": M(rel="23.2 23.3 22.5 22.6"),
 "Container classes": M("23.6"),
 "std::initializer_list": M("23.7 23.x"),
 "Composition over inheritance": M(rel="23.2 24.1"),
 # 19 Inheritance (OOPS 4)
 "What inheritance is": M("24.1"),
 "Basic inheritance": M("24.2"),
 "Order of construction and destruction": M("24.3"),
 "Initializing the base class": M("24.4"),
 "Inheriting constructors": M(rel="24.4", ext=[("cppreference: using-declaration (inheriting constructors)",R("language/using_declaration"))]),
 "Access specifiers in inheritance": M("24.5"),
 "Adding to a derived class": M("24.6"),
 "Overriding inherited functions": M("24.7"),
 "Hiding inherited members": M("24.8"),
 "Multiple inheritance": M("24.9 24.x"),
 # 20 Virtual Functions & Polymorphism (OOPS 5)
 "Base pointers to derived objects": M("25.1"),
 "Virtual functions": M("25.2"),
 "override, final and covariant returns": M("25.3"),
 "Virtual destructors": M("25.4"),
 "Early and late binding": M("25.5"),
 "The virtual table": M("25.6"),
 "Virtual calls in constructors": M(rel="25.2", ext=[("cppreference: virtual functions (during construction and destruction)",R("language/virtual"))]),
 "Pure virtual functions and interfaces": M("25.7"),
 "Virtual base classes and the diamond": M("25.8"),
 "Object slicing": M("25.9"),
 "dynamic_cast": M("25.10"),
 "RTTI and typeid": M(rel="25.10", ext=[("cppreference: typeid",R("language/typeid"))]),
 "Printing derived classes with <<": M("25.11 25.x"),
 "Static polymorphism with CRTP": M(ext=[("cppreference: CRTP",R("language/crtp"))]),
 "The cost of virtual calls": M(rel="25.6"),
 "Type erasure": M(ext=[("cppreference: std::function",R("utility/functional/function")),("cppreference: std::any",R("utility/any"))]),
 # 21 Templates & Classes (OOPS 6)
 "Class templates": M("26.1"),
 "Non-type parameters in class templates": M("26.2"),
 "Function template specialization": M("26.3"),
 "Class template specialization": M("26.4"),
 "Partial specialization": M("26.5"),
 "Partial specialization for pointers": M("26.6 26.x"),
 "Dependent names and typename": M(ext=[("cppreference: dependent names",R("language/dependent_name"))]),
 "Variadic templates": M(ext=[("cppreference: parameter packs",R("language/parameter_pack"))]),
 "Fold expressions": M(ext=[("cppreference: fold expressions",R("language/fold"))]),
 "Template template parameters": M(ext=[("cppreference: template parameters",R("language/template_parameters"))]),
 "Type traits": M(ext=[("cppreference: metaprogramming library",R("meta"))]),
 "SFINAE and enable_if": M(ext=[("cppreference: SFINAE",R("language/sfinae")),("cppreference: std::enable_if",R("types/enable_if"))]),
 "Concepts and requires": M(rel="B.4", ext=[("cppreference: constraints and concepts",R("language/constraints"))]),
 "Template metaprogramming basics": M(ext=[("cppreference: metaprogramming library",R("meta"))]),
 # 22 Exceptions
 "Why exceptions exist": M("27.1"),
 "throw, try and catch": M("27.2"),
 "Stack unwinding": M("27.3"),
 "Uncaught exceptions and catch-all": M("27.4"),
 "Exceptions and class hierarchies": M("27.5"),
 "The standard exception types": M("27.5", ext=[("cppreference: std::exception",R("error/exception"))]),
 "Rethrowing exceptions": M("27.6"),
 "Function try blocks": M("27.7"),
 "Throwing in constructors and destructors": M("27.7 27.8"),
 "Downsides and costs of exceptions": M("27.8"),
 "noexcept": M("27.9"),
 "std::move_if_noexcept": M("27.10 27.x"),
 "Exception safety guarantees": M(rel="27.9", ext=[("cppreference: exceptions (exception safety)",R("language/exceptions"))]),
 "Alternatives: error codes and expected": M(rel="9.4 B.5", ext=[("cppreference: std::expected",R("utility/expected"))]),
 # 23 Input/Output & Streams
 "How I/O streams work": M("28.1"),
 "Input with istream": M("28.2"),
 "Formatting output with ostream": M("28.3"),
 "String streams": M("28.4"),
 "Stream states and validating input": M("28.5"),
 "Reading and writing files": M("28.6"),
 "Random access in files": M("28.7"),
 "Binary file I/O": M(rel="28.6", ext=[("cppreference: std::basic_ostream::write",R("io/basic_ostream/write")),("cppreference: std::basic_istream::read",R("io/basic_istream/read"))]),
 "std::format and std::print": M(rel="B.4 B.5", ext=[("cppreference: std::format",R("utility/format/format")),("cppreference: std::print",R("io/print"))]),
 "std::filesystem": M(rel="B.3", ext=[("cppreference: filesystem library",R("filesystem"))]),
 "Fast I/O for competitive programming": M(ext=[("cppreference: sync_with_stdio",R("io/ios_base/sync_with_stdio"))]),
 # 24 Modern C++ (11–23)
 "What C++11 changed": M("B.1"),
 "C++14 additions": M("B.2"),
 "C++17 additions": M("B.3"),
 "C++20 additions": M("B.4"),
 "C++23 additions": M("B.5"),
 "std::variant and std::any": M(rel="B.3", ext=[("cppreference: std::variant",R("utility/variant")),("cppreference: std::any",R("utility/any"))]),
 "Time with std::chrono": M(rel="18.4", ext=[("cppreference: date and time library",R("chrono"))]),
 "Regular expressions with <regex>": M(ext=[("cppreference: regular expressions library",R("regex"))]),
 "Threads: std::thread and std::jthread": M(ext=[("cppreference: std::thread",R("thread/thread")),("cppreference: std::jthread",R("thread/jthread"))]),
 "Mutexes and locks": M(ext=[("cppreference: std::mutex",R("thread/mutex")),("cppreference: std::scoped_lock",R("thread/scoped_lock"))]),
 "Condition variables": M(ext=[("cppreference: std::condition_variable",R("thread/condition_variable"))]),
 "Atomics and the memory model": M(ext=[("cppreference: std::atomic",R("atomic/atomic")),("cppreference: std::memory_order",R("atomic/memory_order"))]),
 "Futures, promises and std::async": M(ext=[("cppreference: std::future",R("thread/future")),("cppreference: std::async",R("thread/async"))]),
 "Coroutines": M(rel="B.4", ext=[("cppreference: coroutines",R("language/coroutines"))]),
 "Modules": M(rel="B.4", ext=[("cppreference: modules",R("language/modules"))]),
 "Looking ahead to C++26": M(ext=[("cppreference: C++26",R("26"))]),
}

def parse_guides():
    src = open(os.path.join(REPO, "src/content/subtopics.ts")).read()
    guides = []
    for m in re.finditer(r'cpp\(\s*"([^"]+)",\s*"([^"]+)",', src):
        topic, slug = m.group(1), m.group(2)
        # The list's own "]" — skipping strings, since names like "new[]" contain brackets.
        start = src.index("[", m.end())
        body = re.match(r'\[(\s*(?:"(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\')\s*,?)*\s*\]', src[start:]).group(0)
        names = [a or b for a, b in re.findall(r'"((?:[^"\\]|\\.)*)"|\'((?:[^\'\\]|\\.)*)\'', body)]
        guides.append((topic, slug, names))
    return guides

def published():
    """subtopic name -> URL, for every subtopic page that exists in the repo."""
    out = {}
    root = os.path.join(REPO, "content/subtopics/cpp-oops")
    for guide in os.listdir(root) if os.path.isdir(root) else []:
        for sub in os.listdir(os.path.join(root, guide)):
            p = os.path.join(root, guide, sub, "index.md")
            if os.path.isfile(p):
                fm = open(p).read().split("---")[1]
                name = re.search(r"^subtopic:\s*(.+)$", fm, re.M).group(1).strip().strip("'\"")
                out[name] = f"{SITE}/learning/cpp-oops/{guide}/{sub}"
    return out

def link(num):
    title, url = LESSONS[num]
    return f"[{num} {title}]({url})"

def main():
    guides = parse_guides()
    names = [n for _, _, ns in guides for n in ns]
    missing = [n for n in names if n not in MAP]
    extra = [n for n in MAP if n not in names]
    bad = [x for v in MAP.values() for x in v["lessons"] + v["rel"] if x not in LESSONS]
    if missing or extra or bad:
        sys.exit(f"missing={missing}\nextra={extra}\nunknown lessons={bad}")
    live = published()
    used = {x for v in MAP.values() for x in v["lessons"]}
    unmapped = [n for n in LESSONS if n not in used]

    total = len(names)
    own = sum(1 for n in names if not MAP[n]["lessons"])
    lines = [
        "# C++ & OOPs track: review checklist",
        "",
        "Every subtopic on the site, with the sources to check its page against. Our pages are written",
        "in our own words; this file is only for reviewing that nothing was missed. It isn't shown on the site.",
        "",
        "- **learncpp** — the lessons the subtopic covers. Read them alongside our page.",
        "- **Related** — when learncpp has no lesson for the subtopic, the nearest ones that touch it.",
        "- **Reference** — official docs (cppreference, GCC, Clang…) for material learncpp doesn't cover.",
        "- ✅ = page is live (link opens it) · ⏳ = not written yet",
        "",
        f"**{len(live)} of {total} subtopics live.** {total - own} subtopics map to learncpp lessons; "
        f"{own} go beyond learncpp and are checked against reference docs instead.",
        "",
        "Every learncpp lesson is covered by at least one subtopic, except: "
        + ", ".join(link(n) for n in unmapped) + ".",
        "",
        "_Regenerate after each new page: `python3 docs/gen_review.py` (it also fails if a subtopic is missing from the map)._",
        "",
    ]
    for i, (topic, slug, ns) in enumerate(guides, 1):
        done = sum(1 for n in ns if n in live)
        lines += [f"## {i:02d} · {topic}", "",
                  f"[Topic page]({SITE}/learning/cpp-oops/{slug}) · {done}/{len(ns)} live", ""]
        for j, n in enumerate(ns, 1):
            v = MAP[n]
            status = f"✅ [live]({live[n]})" if n in live else "⏳"
            lines.append(f"- **{j:02d} · {n}** · {status}")
            if v["lessons"]: lines.append("  - learncpp: " + " · ".join(link(x) for x in v["lessons"]))
            if v["rel"]: lines.append("  - Related: " + " · ".join(link(x) for x in v["rel"]))
            if v["ext"]: lines.append("  - Reference: " + " · ".join(f"[{a}]({b})" for a, b in v["ext"]))
            if not v["lessons"] and not v["ext"]: lines.append("  - _Our own material._")
        lines.append("")
    out = os.path.join(REPO, "docs/review-track-cpp.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(lines).rstrip("\n") + "\n")
    if "--urls" in sys.argv:  # every link in the file, one per line, for a link check
        urls = sorted({u for _, u in LESSONS.values()} | {u for v in MAP.values() for _, u in v["ext"]})
        print("\n".join(urls))
        return
    print(f"wrote {os.path.relpath(out, REPO)}: {total} subtopics, {len(live)} live, {own} beyond learncpp, unmapped lessons: {unmapped}")

if __name__ == "__main__":
    main()
